name: Sync Docs

on:
  # 手动
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # node v20
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Sync docs
        run: |
          npx giget@latest gh:BuilderIO/qwik/packages/docs#main docs
          ls
      - name: Commit changes
        run: |
          git config --global user.name "Otto_J"
          git config --global user.email "otto@webworker.tech"

          git add .
          git commit -m "Sync docs"
          git push
      # - name: pnpm install
      #   run: |

      #     pnpm install
      # - name: Build
      #   run: |
      #     pnpm run build
